import { Schema, model, Document, Types } from "mongoose";

export interface IDevice extends Document {
  employee: Types.ObjectId;
  deviceId: string; // hardware-derived unique id generated by agent on first run
  hostname: string;
  os: string;
  agentVersion: string;
  enrolledAt: Date;
  lastSeenAt: Date | null;
  isActive: boolean;
}

const DeviceSchema = new Schema<IDevice>(
  {
    employee: { type: Schema.Types.ObjectId, ref: "Employee", required: true },
    deviceId: { type: String, required: true, unique: true },
    hostname: { type: String, required: true },
    os: { type: String, required: true },
    agentVersion: { type: String, required: true },
    enrolledAt: { type: Date, default: Date.now },
    lastSeenAt: { type: Date, default: null },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

DeviceSchema.index({ employee: 1 });

export const Device = model<IDevice>("Device", DeviceSchema);
