import { z } from "zod";

export const enrollDeviceSchema = z.object({
  enrollmentSecret: z.string().min(1),
  employeeCode: z.string().min(1),
  hostname: z.string().min(1),
  os: z.string().min(1),
  agentVersion: z.string().min(1),
  deviceId: z.string().min(8), // hardware-derived fingerprint generated by agent
});

export const activitySessionInputSchema = z.object({
  category: z.enum(["app", "browser_tab"]),
  appName: z.string().min(1).max(200),
  windowTitle: z.string().max(500).default(""),
  url: z.string().url().optional(),
  domain: z.string().max(255).optional(),
  startTime: z.string().datetime(),
  endTime: z.string().datetime(),
  durationSec: z.number().min(0).max(24 * 3600),
});

export const activityMetricInputSchema = z.object({
  bucketStart: z.string().datetime(),
  keystrokeCount: z.number().int().min(0).max(100000),
  mouseClickCount: z.number().int().min(0).max(100000),
  mouseDistancePx: z.number().min(0).max(10_000_000),
  activeSeconds: z.number().min(0).max(60),
});

export const downloadEventInputSchema = z.object({
  filename: z.string().min(1).max(500),
  fileSizeBytes: z.number().min(0).optional(),
  sourceUrl: z.string().url().optional(),
  sourceDomain: z.string().max(255).optional(),
  mimeType: z.string().max(150).optional(),
  downloadedAt: z.string().datetime(),
});

export const idleLogInputSchema = z.object({
  idleStart: z.string().datetime(),
  idleEnd: z.string().datetime(),
  durationSec: z.number().min(0).max(24 * 3600),
});

export const activityBatchSchema = z.object({
  sessions: z.array(activitySessionInputSchema).max(500).default([]),
  metrics: z.array(activityMetricInputSchema).max(1440).default([]),
  downloads: z.array(downloadEventInputSchema).max(200).default([]),
  idleLogs: z.array(idleLogInputSchema).max(200).default([]),
});

export const adminLoginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});
